In [1]:
import time
import numpy as np

In [5]:
G = np.random.randint(20, size=(100,100))
H = np.random.randint(20, size=(100,100))
a = len(G)
d = int(a/2)
row_factor=np.zeros(a)
column_factor = np.zeros(a)
R = np.zeros((a,a))
my_start_time = time.time()

for i in range(a):
    row_factor[i] = G[i][0] * G[i][1]
    for j in range(1, d):
        row_factor[i] += G[i][2*j - 1] * G[i][2*j]
for i in range(a):
    column_factor[i] = H[0][i] * H[1][i]
    for j in range(1,d):
        column_factor[i] += H[2*j - 1][i] * H[2*j][i]
for i in range(a):
    for j in range(a):
        R[i][j] = -(row_factor[i] + column_factor[j])
        for k in range(d):
            R[i][j] += (G[i][2*k-1]+H[2*k][j])*(G[i][2*k] + H[2*k-1][j])            
if (2 * (a/2)!= a):
    for i in range(a):
        for j in range(a):
            R[i][j] += G[i][b] * H[b][j]
print("%s seconds " % (time.time() - my_start_time))
dot_start_time = time.time()

RR = np.dot(G,H)
print("%s seconds" % (time.time() - dot_start_time))

print(G)
print(H)
print(R)

1.2267177104949951 seconds 
0.000997304916381836 seconds
[[ 3 14 13 ... 13 19 18]
 [19  8 18 ...  5 10 17]
 [13  3 12 ...  7 12 14]
 ...
 [12 16  1 ... 12 11 13]
 [17 11 19 ...  9 15  2]
 [ 6  0  8 ...  3 12 17]]
[[15  4 17 ... 19  1 17]
 [ 2  2  3 ... 18 15 17]
 [ 1  0  5 ... 13  0 12]
 ...
 [ 1 18  3 ... 18  4 19]
 [11  7  9 ... 16  2  1]
 [ 0  5  0 ...  6 11 15]]
[[12195.  9835. 10340. ... 11037. 11147. 10773.]
 [10694.  8812.  9002. ...  9394. 10007.  9642.]
 [12152. 10739. 10248. ... 10335. 11306. 10376.]
 ...
 [10120.  8737.  8711. ...  9544. 10569.  8640.]
 [10777.  9565.  9818. ... 10596. 11331.  9451.]
 [10411.  8960.  8514. ...  8744.  8651.  8596.]]
